spring:
  datasource:
    username: root
    password: 417..rty/
    url: jdbc:mysql://localhost:3306/yhy?serverTimezone=UTC&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存时间
      min-evictable-idle-time-millis: 300000

  thymeleaf:
    cache: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true
mybatis:
  type-aliases-package: com.module.entity